name: darwin
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  hydrated_bloc: ^9.1.0
  flutter:
    sdk: flutter
  collection: ^1.17.2
  package_info_plus: ^8.0.0
  flutter_svg: ^2.0.7 
  cupertino_icons: ^1.0.8
  in_app_purchase: ^3.2.3


  provider: ^6.1.1
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  audioplayers: ^5.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15

  just_audio: ^0.9.34  
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter 

  
dev_dependencies:
  hive_generator: ^2.0.1  

  build_runner: ^2.4.6 
  
  flutter_gen_runner: ^5.4.0 

  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
 

  generate: true

  assets:
    - assets/sounds/
    - assets/images/
    - assets/icons/ 
    - assets/background/

# flutter_gen:
#   output: lib/gen/  # Папка для генерации файлов
#   line_length: 80
#   integrations:
#     flutter_svg: true  # Если используете flutter_svg
#   assets:
#     enabled: true
#   colors:
#     enabled: false  # Отключите, если не нужны
#   fonts:
#     enabled: false  # Отключите, если не нужны