import 'package:flutter/material.dart';
import 'package:collection/collection.dart';

class ImageItem {
  final String id;
  final String slug;
  final String assetPath;
  Offset position;
  ImageItem(this.id, this.slug, this.assetPath, {this.position = Offset.zero});
}

final List<ImageItem> allImages = [
  ImageItem('water', 'water', 'assets/images/water.png'),
  ImageItem('cloud', 'cloud', 'assets/images/cloud.png'),
  ImageItem('dna', 'dna', 'assets/images/dna.png'),
  ImageItem('man', 'man', 'assets/images/man.png'),
  ImageItem('morning', 'morning', 'assets/images/morning.png'),
  ImageItem('mushroom', 'mushroom', 'assets/images/mushroom.png'),
  ImageItem('sky', 'sky', 'assets/images/sky.png'),
  ImageItem('sugar', 'sugar', 'assets/images/sugar.png'),
  ImageItem('wind', 'wind', 'assets/images/wind.png'),

  ImageItem('explosion', 'explosion', 'assets/images/explosion.png'),
  ImageItem('radiation', 'radiation', 'assets/images/radiation.png'),
  ImageItem('grape', 'grape', 'assets/images/grape.png'),
  ImageItem('holiday', 'holiday', 'assets/images/holiday.png'),
  ImageItem('knight', 'knight', 'assets/images/knight.png'),
  ImageItem('plane', 'plane', 'assets/images/plane.png'),
  ImageItem('phone', 'phone', 'assets/images/phone.png'),
  ImageItem('car', 'car', 'assets/images/car.png'),

  ImageItem('barista', 'barista', 'assets/images/barista.png'),
  ImageItem('phone_old', 'phone_old', 'assets/images/phone_old.png'),
  ImageItem('wooden', 'wooden', 'assets/images/wooden.png'),
  ImageItem('plankton', 'plankton', 'assets/images/plankton.png'),
  ImageItem('spider', 'spider', 'assets/images/spider.png'),
  ImageItem('glacier', 'glacier', 'assets/images/glacier.png'),
  ImageItem('bacteria', 'bacteria', 'assets/images/bacteria.png'),
  ImageItem('fish', 'fish', 'assets/images/fish.png'),
  ImageItem('tool', 'tool', 'assets/images/tool.png'),
  ImageItem('bicycle', 'bicycle', 'assets/images/bicycle.png'),
  ImageItem('wheel', 'wheel', 'assets/images/wheel.png'),
  ImageItem(
    'crowd_of_people',
    'crowd_of_people',
    'assets/images/crowd_of_people.png',
  ),
  ImageItem('alcohol', 'alcohol', 'assets/images/alcohol.png'),
  ImageItem('stone', 'stone', 'assets/images/stone.png'),
  ImageItem('lizard', 'lizard', 'assets/images/lizard.png'),
  ImageItem('tree', 'tree', 'assets/images/tree.png'),
  ImageItem('swamp', 'swamp', 'assets/images/swamp.png'),
  ImageItem('flour', 'flour', 'assets/images/flour.png'),
  ImageItem('bread', 'bread', 'assets/images/bread.png'),
  ImageItem('banana', 'banana', 'assets/images/banana.png'),
  ImageItem('factory', 'factory', 'assets/images/factory.png'),
  ImageItem('volcano', 'volcano', 'assets/images/volcano.png'),
  ImageItem('city', 'city', 'assets/images/city.png'),
  ImageItem(
    'hungover_saturday_morning',
    'hungover_saturday_morning',
    'assets/images/hungover_saturday_morning.png',
  ),
  ImageItem('cake', 'cake', 'assets/images/cake.png'),
  ImageItem('sailing_ship', 'sailing_ship', 'assets/images/sailing_ship.png'),
  ImageItem(
    'sand_mountain',
    'sand_mountain',
    'assets/images/sand_mountain.png',
  ),
  ImageItem(
    'stone_mountain',
    'stone_mountain',
    'assets/images/stone_mountain.png',
  ),
  ImageItem('metropolis', 'metropolis', 'assets/images/metropolis.png'),
  ImageItem('village', 'village', 'assets/images/village.png'),
  ImageItem('snowman', 'snowman', 'assets/images/snowman.png'),
  ImageItem('love', 'love', 'assets/images/love.png'),
  ImageItem('see', 'see', 'assets/images/see.png'),
  ImageItem('bacterium', 'bacterium', 'assets/images/bacterium.png'),
  ImageItem('monkey', 'monkey', 'assets/images/monkey.png'),
  ImageItem('money', 'money', 'assets/images/money.png'),
  ImageItem('santa_claus', 'santa_claus', 'assets/images/santa_claus.png'),
  ImageItem(
    'new_year_tree',
    'new_year_tree',
    'assets/images/new_year_tree.png',
  ),
  ImageItem('penguin', 'penguin', 'assets/images/penguin.png'),
  ImageItem('witch', 'witch', 'assets/images/witch.png'),
  ImageItem(
    'big_crowd_of_people',
    'big_crowd_of_people',
    'assets/images/big_crowd_of_people.png',
  ),
  ImageItem(
    'noisy_friday_party',
    'noisy_friday_party',
    'assets/images/noisy_friday_party.png',
  ),
  ImageItem('dragon', 'dragon', 'assets/images/dragon.png'),
  ImageItem('book', 'book', 'assets/images/book.png'),
  ImageItem('cow', 'cow', 'assets/images/cow.png'),
  ImageItem('cocktail', 'cocktail', 'assets/images/cocktail.png'),
  ImageItem('cupid', 'cupid', 'assets/images/cupid.png'),
  ImageItem('frog', 'frog', 'assets/images/frog.png'),
  ImageItem(
    'king_of_the_hill',
    'king_of_the_hill',
    'assets/images/king_of_the_hill.png',
  ),
  ImageItem('monument', 'monument', 'assets/images/monument.png'),
  ImageItem('sommelier', 'sommelier', 'assets/images/sommelier.png'),
  ImageItem('snow', 'snow', 'assets/images/snow.png'),
  ImageItem('electricity', 'electricity', 'assets/images/electricity.png'),
  ImageItem('iron', 'iron', 'assets/images/iron.png'),
  ImageItem('acid', 'acid', 'assets/images/acid.png'),
  ImageItem('milk', 'milk', 'assets/images/milk.png'),
  ImageItem('rocket', 'rocket', 'assets/images/rocket.png'),
  ImageItem('intelligence', 'intelligence', 'assets/images/intelligence.png'),
  ImageItem('wood', 'wood', 'assets/images/wood.png'),
  ImageItem('wine', 'wine', 'assets/images/wine.png'),
  ImageItem('swamp', 'swamp', 'assets/images/swamp.png'),
  ImageItem('sun', 'sun', 'assets/images/sun.png'),
  ImageItem('spark', 'spark', 'assets/images/spark.png'),
  ImageItem('robot', 'robot', 'assets/images/robot.png'),
  ImageItem('rainbow', 'rainbow', 'assets/images/rainbow.png'),
  ImageItem('metal', 'metal', 'assets/images/metal.png'),
  ImageItem('mammal', 'mammal', 'assets/images/mammal.png'),

  ImageItem('light', 'light', 'assets/images/light.png'),
  ImageItem('life', 'life', 'assets/images/life.png'),
  ImageItem('fire', 'fire', 'assets/images/fire.png'),
  ImageItem('earth', 'earth', 'assets/images/earth.png'),
  ImageItem('dough', 'dough', 'assets/images/dough.png'),
  ImageItem('dolphin', 'dolphin', 'assets/images/dolphin.png'),
  ImageItem('cat', 'cat', 'assets/images/cat.png'),
  ImageItem('dog', 'dog', 'assets/images/dog.png'),
  ImageItem(
    'artificial_intelligence',
    'artificial_intelligence',
    'assets/images/artificial_intelligence.png',
  ),
  ImageItem('train', 'train', 'assets/images/train.png'),
  ImageItem('mountain', 'mountain', 'assets/images/mountain.png'),
];
